# These are supported funding model platforms
# You can add your funding links here

github: 1231varun
# patreon: your_patreon
# ko_fi: your_kofi
# buy_me_a_coffee: your_bmac
# custom: ["https://your-website.com/donate"]

