# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%  # Allow 5% drop from base
    patch:
      default:
        target: 50%  # Require 50% coverage on new code
        threshold: 10%  # Allow 10% tolerance
        informational: true  # Don't block PRs, just inform

# Ignore files that are hard to test
ignore:
  - "static/**/*"  # CSS, JS, assets
  - "app/templates/**/*"  # HTML templates
  - "launcher.py"  # PyInstaller entry point
  - "build_app.py"  # Build script
  - "run.py"  # Dev server entry

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
